const dataSholat = {
    subuh: {
        judul: "Sholat Subuh (2 Rakaat)",
        langkah: [
            { nama: "Niat", arab: "أُصَلِّى فَرْضَ الصُّبْحِ رَكْعَتَيْنِ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى", latin: "Ushallii fardhash-shubhi rak'ataini mustaqbilal qiblati adaa'an lillaahi ta'aalaa", terjemah: "Aku niat shalat fardu Subuh dua rakaat menghadap kiblat karena Allah Ta'ala." },
            { nama: "Takbiratul Ihram", arab: "اللهُ أَكْبَرُ", latin: "allahu akbar.", terjemah: "Allah Maha Besar." },
            { nama: "Doa Iftitah", arab: "اَللّٰهُ اَكْبَرُ كَبِيْرًا وَالْحَمْدُ لِلّٰهِ كَثِيْرًا وَسُبْحَانَ اللّٰهِ بُكْرَةً وَأَصِيْلًا.إِنِّيْ وَجَّهْتُ وَجْهِيَ لِلَّذِيْ فَطَرَ السَّمَاوَاتِ وَالْأَرْضَ حَنِيْفًا مُسْلِمًا وَمَا أَنَا مِنَ الْمُشْرِكِيْنَ.إِنَّ صَلَاتِيْ وَنُسُكِيْ وَمَحْيَايَ وَمَمَاتِيْ لِلّٰهِ رَبِّ الْعَالَمِيْنَ.لَا شَرِيْكَ لَهُ وَبِذٰلِكَ أُمِرْتُ وَأَنَا مِنَ الْمُسْلِمِيْنَ.",latin: "Allaahu akbar kabiira walhamdulillaahi katsiira, wa subhaanallaahi bukratawwa ashillaa. Innii wajjahtu wajhiya lilladzii fatharas-samaawaati wal ardha haniifan musliman wa maa anaa minal musyrikiin. Inna shalaatii wa nusukii wa mahyaaya wa mamaatii lillaahi Rabbil 'aalamiin. Laa syariikahu wa bidzaalika umirtu wa ana minal muslimiin.", terjemah: "Allah Maha Besar lagi sempurna kebesaran-Nya, segala puji bagi Allah dengan pujian yang sebanyak-banyaknya, dan Maha Suci Allah sepanjang pagi dan petang.Sesungguhnya aku hadapkan wajahku kepada Tuhan yang menciptakan langit dan bumi dengan keadaan lurus dan menyerahkan diri, dan aku bukanlah dari golongan orang-orang musyrik.Sesungguhnya salatku, ibadahku, hidupku, dan matiku hanyalah untuk Allah, Tuhan semesta alam.Tiada sekutu bagi-Nya; dan demikian itulah yang diperintahkan kepadaku dan aku termasuk orang-orang muslim (berserah diri)." },
            { nama: "Surah Al-Fatihah", arab: "١)اَلْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَۙ (٢)الرَّحْمٰنِ الرَّحِيْمِۙ (٣)مٰلِكِ يَوْمِ الدِّيْنِۗ (٤)اِيَّاكَ نَعْبُدُ وَاِيَّاكَ نَسْتَعِيْنُۗ (٥)اِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَۙ (٦)صِرَاطَ الَّذِيْنَ اَنْعَمْتَ عَلَيْهِمْ ەۙ غَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّاۤلِّيْنَ (٧))", latin: "(1)Alhamdu lillaahi Rabbil 'aalamiin(2)Ar-Rahmaanir-Rahiim(3)Maaliki yawmid-diin(4)Iyyaaka na'budu wa iyyaaka nasta'iin(5)Ihdinash-shiraatal-mustaqiim(6)Shiraathalladziina an'amta 'alaihim ghairil-maghdhuubi 'alaihim wa ladh-dhaalliin.", terjemah: "1.Segala puji bagi Allah, Tuhan seluruh alam 2.Yang Maha Pengasih, Maha Penyayang 3.Pemilik hari pembalasan 4.Hanya kepada Engkaulah kami menyembah dan hanya kepada Engkaulah kami mohon pertolongan 5.Tunjukilah kami jalan yang lurus 6.(yaitu) jalan orang-orang yang telah Engkau beri nikmat kepadanya; bukan (jalan) mereka yang dimurkai, dan bukan (pula jalan) mereka yang sesat." },
            { nama: "Ruku'", arab: "سُبْحَانَ رَبِّيَ الْعَظِيْمِ وَبِحَمْدِهِ", terjemah: "Maha Suci Tuhanku Yang Maha Agung dan segala puji bagi-Nya(3x)." },
            { nama: "I'tidal", arab: "سَمِعَ اللّٰهُ لِمَنْ حَمِدَهُ,رَبَّنَا لَكَ الْحَمْدُ مِلْءُ السَّمَاوَاتِ وَمِلْءُ الْأَرْضِ وَمِلْءُ مَا شِئْتَ مِنْ شَيْءٍ بَعْدُ", latin: "Sami'allaahu liman hamidah,Rabbanaa lakal hamdu mil'us-samaawaati wa mil'ul-ardhi wa mil'u maa syi'ta min syai'in ba'du.",terjemah: "Allah mendengar orang yang memuji-Nya,Wahai Tuhan kami, bagi-Mu segala puji, sepenuh langit dan sepenuh bumi, dan sepenuh apa yang Engkau kehendaki sesudah itu." },
            { nama: "Doa Qunut", arab: "اَللّٰهُمَّ اهْدِنِيْ فِيْمَنْ هَدَيْتَ، وَعَافِنِيْ فِيْمَنْ عَافَيْتَ، وَتَوَلَّنِيْ فِيْمَنْ تَوَلَّيْتَ، وَبَارِكْ لِيْ فِيْمَا أَعْطَيْتَ، وَقِنِيْ شَرَّ مَا قَضَيْتَ، فَإِنَّكَ تَقْضِيْ وَلَا يُقْضَى عَلَيْكَ، وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ، وَلَا يَعِزُّ مَنْ عَادَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ، فَلَكَ الْحَمْدُ عَلَى مَا قَضَيْتَ، وَأَسْتَغْفِرُكَ وَأَتُوْبُ إِلَيْكَ، وَصَلَّى اللهُ عَلَى سَيِّدِنَا مُحَمَّدٍ النَّبِيِّ الْأُمِّيِّ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلَّمَ", latin: "Allaahummahdi nii fii man hadait, wa 'aafinii fii man 'aafait, wa tawallanii fii man tawallait, wa baarik lii fii maa a'thait, wa qinii syarra maa qadhait, fa innaka taqdhii wa laa yuqdhaa 'alaik, wa innahu laa yazillu man waalait, wa laa ya'izzu man 'aadait, tabaarakta rabbanaa wa ta'aalait, fa lakal hamdu 'alaa maa qadhait, wa astaghfiruka wa atuubu ilaik, wa shallallaahu 'alaa sayyidinaa muhammadin nabiyyil ummiyyi wa 'alaa aalihii wa shahbihii wa sallam.", terjemah: "Ya Allah, berilah aku petunjuk di antara orang-orang yang Engkau beri petunjuk. Berilah aku kesehatan di antara orang-orang yang Engkau beri kesehatan. Pimpinlah aku di antara orang-orang yang Engkau pimpin. Berilah berkah pada segala apa yang telah Engkau berikan kepadaku. Lindungilah aku dari kejahatan apa yang telah Engkau tetapkan. Sesungguhnya Engkaulah yang memutuskan dan tidak ada yang bisa memutuskan atas-Mu. Sesungguhnya tidak akan hina orang yang Engkau sayangi, dan tidak akan mulia orang yang Engkau musuhi. Maha Berkahlah Engkau, wahai Tuhan kami, dan Maha Tinggi Engkau. Bagi-Mu segala puji atas apa yang telah Engkau tetapkan. Aku memohon ampunan dan bertaubat kepada-Mu. Semoga Allah melimpahkan rahmat dan keselamatan kepada junjungan kami Nabi Muhammad, nabi yang ummi, serta kepada keluarga dan para sahabatnya." },
            { nama: "Sujud", arab: "سُبْحَانَ رَبِّيَ الْأَعْلَى وَبِحَمْدِهِ",latin: "Subhaana rabbiyal a'laa wa bihamdih. (3x)", terjemah: "Maha Suci Tuhanku Yang Maha Tinggi dan segala puji bagi-Nya." },
            { nama: "Duduk diantara dua sujud", arab: "رَبِّ اغْفِرْ لِيْ وَارْحَمْنِيْ وَاجْبُرْنِيْ وَارْفَعْنِيْ وَارْزُقْنِيْ وَاهْدِنِيْ وَعَافِنِيْ وَاعْفُ عَنِّيْ", latin: "Rabbighfirlii warhamnii wajburnii warfa'nii warzuqnii wahdinii wa 'aafinii wa'fu 'annii.", terjemah: "Ya Tuhanku, ampunilah aku, belas kasihanilah aku, cukupkanlah segala kekuranganku, tinggikanlah derajatku, berilah rezeki kepadaku, berilah aku petunjuk, berilah aku kesehatan, dan ampunilah kesalahanku."},
            { nama: "Tahiyat Akhir", arab: "التَّحِيَّاتُ الْمُبَارَكَاتُ الصَّلَوَاتُ الطَّيِّبَاتُ لِلّٰهِ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللّٰهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللّٰهِ الصَّالِحِينَ. أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللّٰهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللّٰهِ.اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى سَيِّدِنَا إِبْرَاهِيمَ وَعَلَى آلِ سَيِّدِنَا إِبْرَاهِيمَ، وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى سَيِّدِنَا إِبْرَاهِيمَ وَعَلَى آلِ سَيِّدِنَا إِبْرَاهِيمَ، فِي الْعَالَمِينَ إِنَّكَ حَمِيدٌ مَجِيدٌ", latin: "Attahiyyaatul mubaarakaatush shalawaatuth thayyibaatu lillaah. Assalaamu 'alaika ayyuhan-nabiyyu wa rahmatullaahi wa barakaatuh. Assalaamu 'alainaa wa 'alaa 'ibaadillaahish-shaalihiin. Asyhadu allaa ilaaha illallaah, wa asyhadu anna Muhammadar Rasuulullaah.Allaahumma shalli 'alaa sayyidinaa Muhammad wa 'alaa aali sayyidinaa Muhammad, kamaa shallaita 'alaa sayyidinaa Ibraahiim wa 'alaa aali sayyidinaa Ibraahiim. Wa baarik 'alaa sayyidinaa Muhammad wa 'alaa aali sayyidinaa Muhammad, kamaa baarakta 'alaa sayyidinaa Ibraahiim wa 'alaa aali sayyidinaa Ibraahiim, fil 'aalamiina innaka hamiidum majiid.", terjemah: "Segala penghormatan yang penuh berkah, keutamaan dan kebaikan adalah milik Allah. Ucapan keselamatan serta rahmat Allah dan berkah-Nya tercurah kepadamu, wahai Nabi. Keselamatan semoga tercurah kepada kami dan kepada hamba-hamba Allah yang saleh. Aku bersaksi bahwa tidak ada Tuhan selain Allah, dan aku bersaksi bahwa Muhammad adalah utusan Allah.Ya Allah, limpahkanlah rahmat kepada junjungan kami Nabi Muhammad dan kepada keluarga junjungan kami Nabi Muhammad, sebagaimana Engkau telah melimpahkan rahmat kepada junjungan kami Nabi Ibrahim dan kepada keluarga junjungan kami Nabi Ibrahim. Dan limpahkanlah berkah kepada junjungan kami Nabi Muhammad dan kepada keluarga junjungan kami Nabi Muhammad, sebagaimana Engkau telah melimpahkan berkah kepada junjungan kami Nabi Ibrahim dan kepada keluarga junjungan kami Nabi Ibrahim, di seluruh alam semesta, sesungguhnya Engkau Maha Terpuji lagi Maha Mulia." },
        ]
    },
    zuhur: {
        judul: "Sholat Zuhur (4 Rakaat)",
        langkah: [
            { nama: "Niat", arab: "أُصَلِّى فَرْضَ الظُّهْرِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى", terjemah: "Aku niat shalat fardu Zuhur empat rakaat menghadap kiblat karena Allah Ta'ala." },
            { nama: "Takbiratul Ihram", arab: "اللهُ أَكْبَرُ", terjemah: "Allah Maha Besar." }
            // ... dst
        ]
    },
    // Lanjutkan polanya untuk ashar, maghrib, isya...
};